### ISSUE TITLE
Clarify which boundary files to use for LAD data

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/apprenticeships-provider-dashboard#8]

**Comment by axcooper** [comment]
Currently the boundary files are from December 2023. However, this only has the current boundaries, and they have changed over the course of the 2 years, and this means that some lads in the earliest year are greyed out. Is is possible to have more than one set of boundaries per map, so that does not have to happen, and the lads shown are the ones valid for that academic year? We could not find a way of doing this in power bi.

**Comment by cjrace** [comment]
Thanks! And yes that's possible, we can do that - when we get to doing that tab I'll download the last few years of boundary files from ONS and then add some extra steps into the data preparation script to join on different boundaries for each year. That way when a user changes the year they're looking at the boundaries will change to match - will mark this as done now
